<template>
  <div class="container-responsive py-8 space-y-8">
    <div class="max-w-4xl mx-auto">
      <div class="card-surface rounded-3xl border border-[var(--surface-border)]/80 p-8 lg:p-12 elegant-shadow">
        <div class="prose prose-lg max-w-none">
          <h1 class="text-4xl font-bold text-[var(--text-strong)] mb-8">Terms of Service</h1>
          
          <p class="text-base text-[var(--text-muted)] mb-6">
            <strong>Last updated:</strong> January 2025
          </p>

          <p class="text-lg text-[var(--text-muted)] leading-relaxed mb-8">
            Welcome to PromptRule! These Terms of Service govern your use of our AI prompt generation service. By using PromptRule, you agree to these terms.
          </p>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">1. Service Description</h2>
          
          <p class="text-base text-[var(--text-muted)] leading-relaxed mb-6">
            PromptRule is a free AI prompt generation service that helps users create effective prompts for various AI models including ChatGPT, Claude, Gemini, and others. Our service includes:
          </p>

          <ul class="list-disc list-inside space-y-2 text-base text-[var(--text-muted)] mb-8">
            <li>AI Prompt Generator for general use cases</li>
            <li>Specialized generators for different AI models</li>
            <li>Prompt optimization and checking tools</li>
            <li>Educational resources and guides</li>
          </ul>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">2. Free Service</h2>
          
          <div class="bg-[var(--surface-50)] rounded-2xl p-6 mb-8">
            <p class="text-base text-[var(--text-muted)] leading-relaxed">
              PromptRule is provided free of charge with no registration required. We reserve the right to implement usage limits or introduce premium features in the future, but the core service will remain free.
            </p>
          </div>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">3. Acceptable Use</h2>
          
          <p class="text-base text-[var(--text-muted)] leading-relaxed mb-6">
            You agree to use PromptRule responsibly and in accordance with all applicable laws. You may not:
          </p>

          <ul class="list-disc list-inside space-y-2 text-base text-[var(--text-muted)] mb-8">
            <li>Use the service for illegal, harmful, or malicious purposes</li>
            <li>Generate prompts intended to create harmful, discriminatory, or offensive content</li>
            <li>Attempt to reverse engineer, hack, or exploit our service</li>
            <li>Use automated tools to overload our servers</li>
            <li>Violate the terms of service of third-party AI services you use our prompts with</li>
            <li>Impersonate others or provide false information</li>
          </ul>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">4. Content Ownership</h2>
          
          <div class="space-y-4 mb-8">
            <div class="border-l-4 border-[var(--accent-blue)] pl-6">
              <h3 class="text-lg font-semibold text-[var(--text-strong)] mb-2">Your Input</h3>
              <p class="text-base text-[var(--text-muted)] leading-relaxed">
                You retain full ownership of any text you input into PromptRule. We do not claim rights to your ideas, requests, or input.
              </p>
            </div>

            <div class="border-l-4 border-[var(--accent-green)] pl-6">
              <h3 class="text-lg font-semibold text-[var(--text-strong)] mb-2">Generated Prompts</h3>
              <p class="text-base text-[var(--text-muted)] leading-relaxed">
                The prompts generated by PromptRule are provided to you for your use. You may use them freely for any lawful purpose, including commercial use.
              </p>
            </div>

            <div class="border-l-4 border-[var(--accent-gold)] pl-6">
              <h3 class="text-lg font-semibold text-[var(--text-strong)] mb-2">PromptRule Service</h3>
              <p class="text-base text-[var(--text-muted)] leading-relaxed">
                The PromptRule service, including our algorithms, frameworks, and website design, remains our intellectual property.
              </p>
            </div>
          </div>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">5. Service Availability</h2>
          
          <p class="text-base text-[var(--text-muted)] leading-relaxed mb-8">
            We strive to maintain high availability of PromptRule, but we cannot guarantee uninterrupted service. We may temporarily suspend service for maintenance, updates, or to address technical issues.
          </p>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">6. Disclaimers</h2>
          
          <div class="bg-yellow-50 border border-yellow-200 rounded-2xl p-6 mb-8">
            <p class="text-base text-[var(--text-muted)] leading-relaxed mb-4">
              <strong>Important:</strong> PromptRule is provided "as is" without warranties of any kind. We make no guarantees about:
            </p>
            <ul class="list-disc list-inside space-y-2 text-base text-[var(--text-muted)]">
              <li>The accuracy or effectiveness of generated prompts</li>
              <li>The results you achieve when using our prompts with AI services</li>
              <li>Continuous availability of the service</li>
              <li>Compatibility with all AI models or platforms</li>
            </ul>
          </div>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">7. Limitation of Liability</h2>
          
          <p class="text-base text-[var(--text-muted)] leading-relaxed mb-8">
            To the fullest extent permitted by law, PromptRule and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service, including but not limited to loss of profits, data, or business opportunities.
          </p>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">8. Third-Party Services</h2>
          
          <p class="text-base text-[var(--text-muted)] leading-relaxed mb-8">
            PromptRule generates prompts for use with third-party AI services (ChatGPT, Claude, etc.). Your use of those services is subject to their respective terms of service. We are not responsible for the policies, practices, or performance of third-party services.
          </p>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">9. Privacy</h2>
          
          <p class="text-base text-[var(--text-muted)] leading-relaxed mb-8">
            Your privacy is important to us. Please review our <NuxtLink to="/privacy" class="text-[var(--accent-blue)] hover:underline">Privacy Policy</NuxtLink> to understand how we handle your information.
          </p>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">10. Changes to Terms</h2>
          
          <p class="text-base text-[var(--text-muted)] leading-relaxed mb-8">
            We may update these Terms of Service from time to time. Changes will be posted on this page with an updated date. Continued use of PromptRule after changes constitutes acceptance of the new terms.
          </p>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">11. Termination</h2>
          
          <p class="text-base text-[var(--text-muted)] leading-relaxed mb-8">
            We reserve the right to terminate or restrict access to PromptRule for users who violate these terms or engage in harmful behavior. You may stop using the service at any time.
          </p>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">12. Governing Law</h2>
          
          <p class="text-base text-[var(--text-muted)] leading-relaxed mb-8">
            These terms are governed by the laws of the jurisdiction where PromptRule operates, without regard to conflict of law principles.
          </p>

          <h2 class="text-2xl font-semibold text-[var(--text-strong)] mb-6">Contact Information</h2>
          
          <p class="text-base text-[var(--text-muted)] leading-relaxed mb-6">
            If you have questions about these Terms of Service, please contact us:
          </p>

          <div class="bg-[var(--surface-50)] rounded-2xl p-6">
            <p class="text-base text-[var(--text-muted)] mb-2">
              <strong>Email:</strong> <a href="mailto:legal@promptrule.com" class="text-[var(--accent-blue)] hover:underline">legal@promptrule.com</a>
            </p>
            <p class="text-base text-[var(--text-muted)]">
              <strong>General Contact:</strong> <a href="mailto:support@promptrule.com" class="text-[var(--accent-blue)] hover:underline">support@promptrule.com</a>
            </p>
          </div>

          <div class="mt-8 p-6 bg-gradient-to-r from-[var(--accent-blue)]/10 to-[var(--accent-teal)]/10 rounded-2xl text-center">
            <p class="text-base text-[var(--text-muted)] mb-4">
              By using PromptRule, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
            </p>
            <NuxtLink to="/" class="btn-primary hover-lift inline-flex items-center justify-center">
              Start Using PromptRule
            </NuxtLink>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Set page meta
useHead({
  title: 'Terms of Service - PromptRule AI Prompt Generator',
  meta: [
    {
      name: 'description',
      content: 'PromptRule Terms of Service: Learn about acceptable use, content ownership, and our commitment to providing free AI prompt generation tools for everyone.'
    }
  ]
})
</script>
